
name: CD sapper
# events but only for the master branch
on:
  push:
    branches:
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # The type of runner that the job will run on
  publish-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
    - uses: actions/setup-node@v1
    #- name: create docs dir
    #  run:  mkdir ./docs       
    - name: Use Node.js 12.x
      run: |
        npm install
        npm run export
    # - name: Delete multiple branches
    #   uses: dawidd6/action-delete-branch@v3.0.0
    #   with:
    #     branches: gh-pages # Branches to delete (comma separated)
    - name: copy to root dir
      run: |
        git checkout -b gh-pages
        shopt -s extglob
        rm -rf !(__sapper__|.git|.gitignore)
        cp -r ./__sapper__/export/* .
        rm -rf __sapper__
        ls -la
        git add .
        git commit -m "autocommit gh-pages"
        git push
    - name: Publish to GitHub Pages
      uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
      with:
        # The name of the directory that containing the content to be published
        #dir:  # optional, default is ./
        # The name of the remote branch that publishing source for GitHub Pages site
        branch: gh-pages
        # The remote repository that publishing source for GitHub Pages site, defaults to current repo and is formatted like 'user/repo-name'
        #repo: # optional
        # The personal access token that authorize repo access
        token: ${{github.token}}
